Fix/xcloc
b123400/xliffie pull request #6
Opened 2019-01-02 03:32 UTC by harrisong

Fixes #5 

- [x]  Support opening the .xcloc folders, the behaviour should be the same as opening the inner .xliff file.
  - [x] Double click on the folder should open Xliffie
- [x]  Associate multiple .xcloc folders to the same window, just like how xliff files are associated
- [ ]  The app should still be able to support the old folder structure

2019-01-07 07:26 UTC, b123400 requested changes
Thank you so much! I find some issues though:

1. When opening with "drag to dock icon" or double clicking xcloc folder
    - It fails to associate multiple .xcloc folders to the same window (Every xcloc folder got its own window)
    - This does not happen when opening via "File -> Open..." menu
2. When opening a xcloc file with the "File -> Open..." menu
    1. Edit any translation
    2. Press command+s to save
    3. The original xcloc folder is now a xml file.

------

In case 1. When "drag to dock icon" or double clicking xcloc folder, although the user is operating on a xcloc folder, we are actually opening the internal Xliff file. That's why you see in the title bar, it says 
"xxx.xliff" instead of "xxx.xcloc". Which means the `Document` object is pointing to an xliff file. (`document.fileUrl`)

In case 2. When the user opens a xcloc folder with the "File -> Open..." menu, we are actually "opening" a xcloc folder. You can see the title bar saying "xxx.xcloc". Which means the `Document` object is pointing to an xcloc folder. (`document.fileUrl`). So it writes to the xcloc location instead of the internal xliff file.

After reading the NSDocument and NSFileWrapper documentation for a while, I think maybe the current approach is not enough.

----

There are 2 choices I can think of:

# Plan A. Always open Xliff file.
    
- Make sure the Document class always, and only refers to Xliff file, instead of xcloc.
    - I am not sure if this is possible, it will be like, the app is not opening the exact file the user is clicking on.
- Update `-[AppDelegate openedDocumentControllerWithPath:]` so that multiple xliff files can be associated at xcloc level.
    - This is the method that, when a Document is opened, it would ask "Is there any existing window I can join?"
    - The [current implementation](https://github.com/b123400/xliffie/blob/16a987edb7ee87290e7b16ea0be45640ef95035e/Xliffie/AppDelegate.m#L105-L115) is, as long as they are in the same folder, they are associated.
    - Modifying this function should be able to fix case 1.

# Plan B. Open both Xcloc folder and Xliff file properly.

- When a user opens a Xcloc folder, we open it as if it's a document.
- It should be the Document class (or its subclass) who do the "Xcloc -> Xliff" reading
- The Document class should implement [`-[NSDocument fileWrapperOfType:error:]`](https://developer.apple.com/documentation/appkit/nsdocument/1515089-filewrapperoftype?language=objc) such that saving a xcloc folder is possible
    - This should fix case 2.
- This plan can be implemented by either
    A. Adding a few new variables to the Document class, so that the Document remembers "I am a file wrapper, my fileURL is not the same as the xliff URL that I should write to"
    B. Create a subclass of Document (lets call it XclocDocument), and update Info.plist to use the class

2019-01-07 07:26 UTC, b123400 commented on Xliffie/AppDelegate.m
> +                    thisItem = [NSString stringWithFormat:@"%@/%@", thisItem, @"Localized Contents"];
use [this method](https://developer.apple.com/documentation/foundation/nsstring/1417069-stringbyappendingpathcomponent?language=objc) seems better

2019-01-07 07:26 UTC, b123400 commented on Xliffie/Document.m
> +                [[[fw filename] pathExtension] isEqualToString:@"xlf"]) {
I think we better put these repeated file extension checking logics into a separated function

2019-01-07 07:26 UTC, b123400 commented on Xliffie/Document.m
> +    if ([[[fileWrapper filename] pathExtension] isEqualToString:@"xliff"] ||
lets add `[fileWrapper isRegularFile]` too

2019-01-07 07:26 UTC, b123400 commented on Xliffie/Document.m
> +            if ([[fw filename] isEqualToString:@"Localized Contents"]) {
We better add `[fw isDirectory]` here too, it's possible to have symlink as a FileWrapper, then we might have infinite recursion. Lets not handle symlink at the moment.

2019-02-21 08:38 UTC, closed without merging

2019-02-21 08:39 UTC, harrisong commented
Closing this as moved to https://git.sr.ht/~not/xliffie/log/fix/xcloc